CurrencyConverter/Controllers/ExchangeController.cs
using CurrencyConverter.Entities;
using CurrencyConverter.Models;
using CurrencyConverter.Models.ExchangeVM;
using CurrencyConverter.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading.Tasks;

namespace CurrencyConverter.Controllers
{
	enum CurrencyDataCondition
	{
		convertedFromCurrency,
		convertedToCurrency
	}

	public class ExchangeController : Controller
	{
		private readonly ICurrencyTypeService _currencyTypesService;
		private readonly ICurrencyExchangeService _currencyExchangeService;	
		public ExchangeController(ICurrencyTypeService currencyService, ICurrencyExchangeService currencyExchangeService)
		{
			_currencyTypesService = currencyService;
			_currencyExchangeService = currencyExchangeService;
		}

		public async Task<IActionResult> Index()
		{
			var twoCurrenciesList = _currencyTypesService.GetExchangeCurrenciesLists();

			ViewBag.ListOfCurrency_1 = twoCurrenciesList.First;
			ViewBag.ListOfCurrency_2 = twoCurrenciesList.Second;

			return await Task.Run(() => View());
		}

		public async Task<IActionResult> GetCurrencyTypesSelectionList()
		{
			var currencyTypesList = _currencyTypesService.GetAllCurrenciesLists();
			return await Task.Run(() => View(currencyTypesList));
		}

		[HttpPost]
		public async Task<IActionResult> SaveSelectedCurrencyForExchange(List<CurrencyTypesSelectionVM> selectedCurrencyList)
		{
			_currencyTypesService.UpdateSelectedCurrencyList(selectedCurrencyList);
			return await Task.Run(() => RedirectToAction("Index"));
		}


		[HttpPost]
		public JsonResult Index(string[] exchangeOperationData)
		{
			var style = NumberStyles.Number | NumberStyles.AllowCurrencySymbol;
			var culture = CultureInfo.CreateSpecificCulture("en-GB");

			var exchangeResultModel = new ExchangeOperationResultVM();
			if (Double.TryParse(exchangeOperationData[1], style, culture, out double firstAmount) &&
				Double.TryParse(exchangeOperationData[3], style, culture, out double secondAmount))
			{
				exchangeResultModel = _currencyExchangeService.GetCurrencyExchangeResultModel(exchangeOperationData);
				return Json(exchangeResultModel);
			}
			return Json("Bad responce");
		}

		public async Task<IActionResult> GetExchangesList(ExchangeOperationFilterVM filter, int page = 1)
		{
			var model = _currencyExchangeService.GetExchangeOperations(filter, page);

			ViewBag.StaticticModel_1 = _currencyExchangeService.GetCurrencyChartData(CurrencyDataCondition.convertedFromCurrency.ToString());
			ViewBag.StaticticModel_2 = _currencyExchangeService.GetCurrencyChartData(CurrencyDataCondition.convertedToCurrency.ToString());

			ViewBag.CurrentSortOrder = filter.SortOrder;  
			ViewData["Id_Sorting_Order"] = filter.SortOrder == "Id_asc" ? "Id_desc" : "Id_asc";
			ViewData["From_Amount_Sorting_Order"] = filter.SortOrder == "from_amount_asc" ? "from_amount_desc" : "from_amount_asc";
			ViewData["Converted_Amount_Sorting_Order"] = filter.SortOrder == "converted_amount_asc" ? "converted_amount_desc" : "converted_amount_asc";			
			ViewData["Date_Sorting_Order"] = filter.SortOrder == "date_order_asc" ? "date_order_desc" : "date_order_asc";

			return await Task.Run(() => View(model));
		}

		

		
	}
}

CurrencyConverter/Views/Exchange/GetCurrencyTypesSelectionList.cshtml
@model List<CurrencyConverter.Models.ExchangeVM.CurrencyTypesSelectionVM>

@{
	Layout = null;
	var model = Model;
}

<div>
	@using (Html.BeginForm("SaveSelectedCurrencyForExchange", "exchange", FormMethod.Post))
	{
		<table class="table table-striped table-sm table-hover">
			<thead>
				<tr>
					<th scope="col">Id</th>
					<th scope="col" class="text-center">Currency</th>
					<th scope="col" class="text-center">For exchange</th>
				</tr>
			</thead>
			<tbody>
				@for (int i = 0; i < Model.Count(); i++)
				{
					<tr>
						<td >
							@Html.DisplayFor(m => m[i].Id)							
						</td>
						<td class="text-center">
							@Html.DisplayFor(m => m[i].Name)
							@Html.HiddenFor(m => m[i].Name)
						</td>
						<td class="text-center">
							@Html.CheckBoxFor(m => m[i].IsSelected)
							@Html.HiddenFor(m => m[i].Id)
						</td>
					</tr>
				}
			</tbody>
		</table>
		<hr />
		<input  class="btn btn-primary float-right" type="submit" style="width:100px;" value="Save" />
	}
</div>

CurrencyConverter/Views/Exchange/GetExchangesList.cshtml
@using CurrencyConverter.Models.ExchangeVM
@using CurrencyConverter.Models.StatisticVM
@model ExchangeOperationVM
@{
	ViewData["Title"] = "GetExchangesList";
}
@{
	int page = Model.Page;
	var chartData_1 = ViewBag.StaticticModel_1;
	var chartData_2 = ViewBag.StaticticModel_2;
}


<h1 class="text-center">Exchange history</h1>
@await Html.PartialAsync("_SearchData", Model.ExchangeOperationsFilter)


<hr />
<div class="row justify-content-center">
	<div class="col-md-12">
		<table class="table table-striped table-sm table-hover">
			<thead class="thead-dark">
				<tr>
					<th>
						<a asp-action="GetExchangesList"
						   asp-route-page="@(page)"
						   asp-route-sortOrder="@ViewData["Id_Sorting_Order"]"
						   asp-route-id="@Model.ExchangeOperationsFilter.Id"
						   asp-route-fromcurrency="@Model.ExchangeOperationsFilter.FromCurrency"
						   asp-route-fromamount="@Model.ExchangeOperationsFilter.FromAmount"
						   asp-route-tocurrency="@Model.ExchangeOperationsFilter.ToCurrency"
						   asp-route-toamount="@Model.ExchangeOperationsFilter.ToAmount"
						   asp-route-publishtimesincefield="@Model.ExchangeOperationsFilter.PublishTimeSinceField"
						   asp-route-publishtimetillfield="@Model.ExchangeOperationsFilter.PublishTimeTillField">Id</a>
					</th>
					<th scope="col">Convert From</th>
					<th>
						<a asp-action="GetExchangesList"
						   asp-route-page="@(page)"
						   asp-route-sortOrder="@ViewData["From_Amount_Sorting_Order"]"
						   asp-route-id="@Model.ExchangeOperationsFilter.Id"
						   asp-route-fromcurrency="@Model.ExchangeOperationsFilter.FromCurrency"
						   asp-route-fromamount="@Model.ExchangeOperationsFilter.FromAmount"
						   asp-route-tocurrency="@Model.ExchangeOperationsFilter.ToCurrency"
						   asp-route-toamount="@Model.ExchangeOperationsFilter.ToAmount"
						   asp-route-publishtimesincefield="@Model.ExchangeOperationsFilter.PublishTimeSinceField"
						   asp-route-publishtimetillfield="@Model.ExchangeOperationsFilter.PublishTimeTillField">Amount From</a>
					</th>
					<th scope="col">Convert To</th>
					<th>
						<a asp-action="GetExchangesList"
						   asp-route-page="@(page)"
						   asp-route-sortOrder="@ViewData["Converted_Amount_Sorting_Order"]"
						   asp-route-id="@Model.ExchangeOperationsFilter.Id"
						   asp-route-fromcurrency="@Model.ExchangeOperationsFilter.FromCurrency"
						   asp-route-fromamount="@Model.ExchangeOperationsFilter.FromAmount"
						   asp-route-tocurrency="@Model.ExchangeOperationsFilter.ToCurrency"
						   asp-route-toamount="@Model.ExchangeOperationsFilter.ToAmount"
						   asp-route-publishtimesincefield="@Model.ExchangeOperationsFilter.PublishTimeSinceField"
						   asp-route-publishtimetillfield="@Model.ExchangeOperationsFilter.PublishTimeTillField">Converted Amount</a>
					</th>
					<th>
						<a asp-action="GetExchangesList"
						   asp-route-page="@(page)"
						   asp-route-sortOrder="@ViewData["Date_Sorting_Order"]"
						   asp-route-id="@Model.ExchangeOperationsFilter.Id"
						   asp-route-fromcurrency="@Model.ExchangeOperationsFilter.FromCurrency"
						   asp-route-fromamount="@Model.ExchangeOperationsFilter.FromAmount"
						   asp-route-tocurrency="@Model.ExchangeOperationsFilter.ToCurrency"
						   asp-route-toamount="@Model.ExchangeOperationsFilter.ToAmount"
						   asp-route-publishtimesincefield="@Model.ExchangeOperationsFilter.PublishTimeSinceField"
						   asp-route-publishtimetillfield="@Model.ExchangeOperationsFilter.PublishTimeTillField">Convertation Date</a>
					</th>
				</tr>
			</thead>
			<tbody>
				@*<img src="/Files/@item.Image" width="100"></td>*@
				@foreach (var item in Model.ExOpList)
				{
					<tr id="row_@item.Id">
						<th scope="row">@item.Id</th>
						<td>@item.FromCurrency</td>
						<td>@item.FromAmount</td>
						<td>@item.ToCurrency</td>
						<td>@item.ToAmount</td>
						<td>@item.DateCreate.ToString()</td>
					</tr>
				}
			</tbody>
		</table>

		<nav class="d-flex justify-content-center">
			<ul class="pagination">
				<li class="page-item @(page == 1? "disabled":"")">
					<a class="page-link"
					   asp-action="GetExchangesList"
					   asp-controller="Exchange"
					   asp-route-page="@(page - 1)"
					   asp-route-sortOrder="@ViewBag.CurrentSortOrder"
					   asp-route-id="@Model.ExchangeOperationsFilter.Id"
					   asp-route-fromcurrency="@Model.ExchangeOperationsFilter.FromCurrency"
					   asp-route-fromamount="@Model.ExchangeOperationsFilter.FromAmount"
					   asp-route-tocurrency="@Model.ExchangeOperationsFilter.ToCurrency"
					   asp-route-toamount="@Model.ExchangeOperationsFilter.ToAmount"
					   asp-route-publishtimesincefield="@Model.ExchangeOperationsFilter.PublishTimeSinceField"
					   asp-route-publishtimetillfield="@Model.ExchangeOperationsFilter.PublishTimeTillField"
					   asp-route-publishtimetill="@Model.ExchangeOperationsFilter.PublishTimeTill"
					   asp-route-publishtimesince="@Model.ExchangeOperationsFilter.PublishTimeSince"
					   tabindex="-1">
						Prev
					</a>
				</li>
				@for (int i = 1; i < Model.MaxPage + 1; i++)
				{
					<li class="page-item @(page == i ? "active": "" )">
						<a class="page-link"
						   asp-action="GetExchangesList"
						   asp-controller="Exchange"
						   asp-route-page="@i"
						   asp-route-sortOrder="@ViewBag.CurrentSortOrder"
						   asp-route-id="@Model.ExchangeOperationsFilter.Id"
						   asp-route-fromcurrency="@Model.ExchangeOperationsFilter.FromCurrency"
						   asp-route-fromamount="@Model.ExchangeOperationsFilter.FromAmount"
						   asp-route-tocurrency="@Model.ExchangeOperationsFilter.ToCurrency"
						   asp-route-toamount="@Model.ExchangeOperationsFilter.ToAmount"
						   asp-route-publishtimesincefield="@Model.ExchangeOperationsFilter.PublishTimeSinceField"
						   asp-route-publishtimetillfield="@Model.ExchangeOperationsFilter.PublishTimeTillField"
						   asp-route-publishtimetill="@Model.ExchangeOperationsFilter.PublishTimeTill"
						   asp-route-publishtimesince="@Model.ExchangeOperationsFilter.PublishTimeSince">
							@i <span class="sr-only">(current)</span>
						</a>
					</li>
				}
				@*asp-route-sortOrder="@ViewBag.CurrentSortOrder"*@
				<li class="page-item @(page == Model.MaxPage? "disabled":"")">
					<a class="page-link"
					   asp-action="GetExchangesList"
					   asp-controller="Exchange"
					   asp-route-page="@(page+1)"
					   asp-route-sortOrder="@ViewBag.CurrentSortOrder"
					   asp-route-id="@Model.ExchangeOperationsFilter.Id"
					   asp-route-fromcurrency="@Model.ExchangeOperationsFilter.FromCurrency"
					   asp-route-fromamount="@Model.ExchangeOperationsFilter.FromAmount"
					   asp-route-tocurrency="@Model.ExchangeOperationsFilter.ToCurrency"
					   asp-route-toamount="@Model.ExchangeOperationsFilter.ToAmount"
					   asp-route-publishtimesincefield="@Model.ExchangeOperationsFilter.PublishTimeSinceField"
					   asp-route-publishtimetillfield="@Model.ExchangeOperationsFilter.PublishTimeTillField"
					   asp-route-publishtimetill="@Model.ExchangeOperationsFilter.PublishTimeTill"
					   asp-route-publishtimesince="@Model.ExchangeOperationsFilter.PublishTimeSince">
						Next
					</a>
				</li>
			</ul>
		</nav>
	</div>
</div>
@await Html.PartialAsync("_StaticticCharts", (StatisticVM)ViewBag.StaticticModel)


@section scripts
{
	@*<script src="~/lib/chart.js/dist/Chart.min.js"></script>*@

<script type="text/javascript">
		function ChangeDate(id) {
			console.log("work");
			var x = document.getElementById(id).value;

			var date = x.substr(8) + "." + x.substr(5, 2) + "." + x.substr(0, 4);
			var htmlItem = "DateField_" + id.substr(11);

			console.log(x);
			document.getElementById(htmlItem).value = date;
			console.log("work");
		}

		function cleanFunction() {
			document.getElementById("DateField_1").value = "";
			document.getElementById("DateField_2").value = "";
			document.getElementById("FromCurrencyField").value = "";
			document.getElementById("ToCurrencyField").value = "";

			console.log("work")
		}

	let Chart_1 = document.getElementById("chart_1").getContext('2d');
	let Chart_2 = document.getElementById("chart_2").getContext('2d');

	let chart1 = new Chart(Chart_1, {
		type: 'doughnut',
		data: {
			labels: [
				@foreach (var item in chartData_1.ListChartDataItems)
				{
					@:"@Html.Raw(item.SectorLabel)",
				}
			],
			datasets: [{
				data: [
					@foreach (var item in chartData_1.ListChartDataItems)
					{
						@:"@Html.Raw(item.SectorValue)",
					}
				],
				backgroundColor: [
					@foreach (var item in chartData_1.ListChartDataItems)
					{
						@:"@Html.Raw(item.SectorColor)",
					}
				]
			}]
		},
		options: {
			title: {
				text: "Currency types converted from ( % )",
				display: true
			}
		}
	});

	let chart2 = new Chart(Chart_2, {
		type: 'doughnut',
		data: {
			labels: [
				@foreach (var item in chartData_2.ListChartDataItems)
				{
					@:"@Html.Raw(item.SectorLabel)",
				}
			],
			datasets: [{
				data: [
					@foreach (var item in chartData_2.ListChartDataItems)
					{
						@:"@Html.Raw(item.SectorValue)",
					}
				],
				backgroundColor: [
					@foreach (var item in chartData_2.ListChartDataItems)
					{
						@:"@Html.Raw(item.SectorColor)",
					}
				]
			}]
		},
		options: {
			title: {
				text: "Currency types converted to ( % )",
				display: true
			}
		}
	});



			//$("#SubmitFilter").on("click", function () {
			//	var filterValue = $("#_sortOrder").val();
			//	console.log("filterValue: ", filterValue);

			//	$("#sortOrder").val(filterValue);
			//})

</script>
}

CurrencyConverter/Views/Exchange/Index.cshtml
@model CurrencyConverter.Models.CurrencyTypeVM


<link href="~/css/validation.css" rel="stylesheet" />
<h2 class="text-center" style="margin-bottom: 100px;">Currency Exchange</h2>
<h4 id="warning" class="text-center text-danger" style="margin-bottom: 20px;"></h4>
<div class="container">
	<div class="row ">
		<div class="col-md-12">
			<form>
				<div class="validation" asp-validation-summary="ModelOnly"></div>
				<div class="container">
					<div class="row text-center">
						<div class="col-md-3">
							<div class="form-group">
								<input id="FirstCurrencyAmount" class="form-control" type="text" placeholder="amount" asp-for="LeftCurrencyAmount">
								<span asp-validation-for="LeftCurrencyAmount" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-2">
							<select id="FirstCurrList"
									name="_FirstCurrList"
									asp-for="Id"
									class="form-control"
									asp-items="@(new SelectList(ViewBag.ListOfCurrency_1, "Id", "Name"  ))">
							</select>
						</div>
						<div class="col-md-1 text-center">
							<i id="Reverce" class="fas fa-exchange-alt fa-2x" style="color:green"></i>
						</div>
						<div class="col-md-3">
							<div class="form-group">
								<input id="SecondCurrencyAmount" class="form-control" type="text" placeholder="amount" asp-for="RightCurrencyAmount">
								<span asp-validation-for="RightCurrencyAmount" class="text-danger"></span>
							</div>

						</div>
						<div class="col-md-2">
							<select id="SecondCurrList"
									asp-for="Id"
									name="_SecondCurrList"
									class="form-control"
									asp-items="@(new SelectList(ViewBag.ListOfCurrency_2, "Id", "Name"  ))">
							</select>
						</div>
					</div>
				</div>
			</form>

		</div>
	</div>
	<div class="container">
		<div class="row ">
			<div class="col-md-6" style="margin-top: 10px">
				<div id="ResultBox">
					<div id="Result">
						<h3 style="display: inline;"></h3>
						<h3 style="display: inline; color:green"></h3>
						<h3 style="display: inline;"></h3>
					</div>
				</div>
			</div>
			<div class="col-md-3" style="margin-top: 20px; padding-right: 0px;">
				<input id="currMenu" onclick="getCurrencySelectionList()"  type="button" value="Select currency" class="btn btn-primary float-right" />
			</div>
			<div class="col-md-2" style="margin-top: 20px; padding-left: 0px;">
				<input id="Submit1" type="button" value="Exchange" class="btn  btn-success float-right" />
			</div>
		</div>
	</div>



	<div class="modal fade" id="currModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" id="dialogContent" role="document">
			<div class="modal-content">
				<div class="modal-header text-center">
					<h5 class="modal-title " id="exampleModalLabel">Currency List</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">

				</div>
				@*<div class="modal-footer">					
				</div>*@
			</div>
		</div>
	</div>
</div>


@section scripts{
	<script type="text/javascript">

		function getCurrencySelectionList() {
			console.log("selction!");
			$.get("@Url.Action("GetCurrencyTypesSelectionList", "Exchange")",
				function (data) {
					$('.modal-body').html(data);
				})
			$('#currModal').modal('show');
		}	


		//$('#Reverce').on("click", function () {
		//	var selectedItem_1 = $("#FirstCurrList option:selected").text();
		//	var selectedItem_2 = $("#SecondCurrList option:selected").text();

		//	console.log("FIRST:", selectedItem_1, selectedItem_2);

		//	var ind_1 = $('select[name="_FirstCurrList"]').val();
		//	var ind_2 = $('select[name="_SecondCurrList"]').val()

		//	console.log("SECOND", ind_1, ind_2);

		//	$("#FirstCurrList").val(ind_2);
		//	$("#SecondCurrList").val(ind_1);

		//	console.log("THIRD:", selectedItem_1, selectedItem_2);
		//})

		$("#Submit1").on("click", function () {
			var selectedItem_1 = $("#FirstCurrList option:selected").text();
			var selectedItem_2 = $("#SecondCurrList option:selected").text();
			var firstSum = $("#FirstCurrencyAmount").val();
			var secondSum = $("#SecondCurrencyAmount").val();

			var exchangeData = [selectedItem_1, firstSum, selectedItem_2, secondSum];

			console.log("exchangeData: ", exchangeData)
			if (parseFloat(firstSum) > 0 && parseFloat(secondSum) > 0) {
				console.log("firstSum: ", firstSum, "secondSum: ", secondSum)
				$('#warning').text("one currency amount should be 0 or empty");
				return;
			}

			if (parseFloat(firstSum) < 0 || parseFloat(secondSum) < 0) {
				console.log("firstSum: ", firstSum, "secondSum: ", secondSum)
				$('#warning').text("possible convert only positive amounts");
				return;
			}

			if (firstSum == "" || firstSum == null) {
				exchangeData[1] = "0";
			}
			if (secondSum == "" || secondSum == null) {
				exchangeData[3] = "0";
			}


			$.ajax({
				url: '@Url.Action("Index")',
				type: "POST",
				data: { exchangeOperationData: exchangeData  },
				dataType: "json",
				success: function (responce) {

					if (responce == 'Bad responce') {
						$('#warning').text("incorrect populated data");
						$("#Result").remove();
					}
					else {
						$("#Result").remove();
						$("#warning").html("");
						console.log("good resp: ", responce)
						if (firstSum == "" || firstSum == "0" || firstSum == "amount") {
							$('#FirstCurrencyAmount').val(responce.convertedAmountResult);
						}
						else {
							$('#SecondCurrencyAmount').val(responce.convertedAmountResult);
						}
						$('#ResultBox').append("<div id=\"Result\">" +
							"<h3 style=\"display: inline;\">1 " + responce.currencyFromType + " = " + "</h3>" +
							"<h3 style=\"display: inline; color:green\">" + responce.exchangeCourse + "  " + "</h3>" +
							"<h3 style=\"display: inline;\">" + responce.currencyToType + "</h3>" +
							"</div> ");
					}
				},
				failure: function (responce) {
					console.log("bad resp: ", responce)
				}
			});
		})
	</script>
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"
		asp-fallback-src="~/lib/jquery-validation/dist/jquery.validate.min.js"
		asp-fallback-test="window.jQuery && window.jQuery.validator">
</script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"
		asp-fallback-src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"
		asp-fallback-test="window.jQuery && window.jQuery.validator && window.jQuery.validator.unobtrusive">
</script>

CurrencyConverter/Views/Exchange/_SearchData.cshtml
@model CurrencyConverter.Models.ExchangeOperationFilterVM

<h1 class="text-center"></h1>
<hr />

@{ var test = Model.SortOrder; }
<div class="container">
	<div class="row">
		<div class="col-md-12" style="padding:0px;">
			<form asp-action="GetExchangesList" asp-controller="Exchange" method="get">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group row" style="margin:0px;">
					<div class="col-sm-5" style="padding:0px;">
						<div class="input-group mb-3">
							<div class="input-group-prepend">
								<span class="input-group-text">Converted From</span>
							</div>
							<input asp-for="FromCurrency" id="FromCurrencyField" class="form-control w-50" />
							<span asp-validation-for="FromCurrency" class="text-danger"></span>
						</div>
					</div>
					<div class="col-sm-4 form-inline mb-5">
						<div class="input-group-prepend">
							<span class="input-group-text"
								  style="border-top-right-radius: 0px;
									border-bottom-right-radius: 0px;">
								Since:
							</span>
						</div>
						<input asp-for="PublishTimeSinceField" type="text" id="DateField_1" placeholder="DD.MM.YYYY" class="form-control"
							   style="border-top-right-radius: 0px;
									border-bottom-right-radius: 0px;
									border-top-left-radius: 0px;
									border-bottom-left-radius: 0px;" />

						<input asp-for="PublishTimeSince" id="DatePicker_1" type="date"
							   class="form-control"
							   style="width:63px; height:38px;
										background-color: lightgray ;
										padding-left:0px;
										border-top-left-radius: 0px;
										border-bottom-left-radius: 0px;
										margin-right: 10px;"
							   onchange="ChangeDate(this.id)" />
						<span asp-validation-for="PublishTimeSinceField" class="text-danger"></span>
					</div>
				</div>

				<div class="form-group row" style="margin:0px;">
					<div class="col-sm-5" style="padding:0px;">
						<div class="input-group mb-3">
							<div class="input-group-prepend">
								<span class="input-group-text">Converted To</span>
							</div>
							<input asp-for="ToCurrency" id="ToCurrencyField" class="form-control w-50" />
							<span asp-validation-for="ToCurrency" class="text-danger"></span>
						</div>
					</div>
					<div class="col-sm-4 form-inline mb-5">
						<div class="input-group-prepend">
							<span class="input-group-text"
								  style="border-top-right-radius: 0px;
										border-bottom-right-radius: 0px;
										width: 66px;">Till:
							</span>
						</div>
						<input asp-for="PublishTimeTillField"
							   type="text"
							   id="DateField_2"
							   placeholder="DD.MM.YYYY" class="form-control"
							   style="border-top-right-radius: 0px;
									  border-bottom-right-radius: 0px;
									  border-top-left-radius: 0px;
									  border-bottom-left-radius: 0px;" />
						<input asp-for="PublishTimeTill"
							   type="date"
							   id="DatePicker_2"
							   class="form-control"
							   style="width:63px; height:38px; background-color: lightgray ; padding-left:0px;
									  border-top-left-radius: 0px;
									  border-bottom-left-radius: 0px;
									  margin-right: 10px;"
							   onchange="ChangeDate(this.id)" />
						<span asp-validation-for="PublishTimeTillField" class="text-danger"></span>

						<input asp-for="SortOrder"
							   class="form-control"
							   type="hidden" id="sortOrder">
					</div>
					<div class="col mb-5" style="padding:0px;">
						<input type="button"
							   style="background-color: darkviolet;
							   color: #fff; width:150px;
							   margin-left:12px;"
							   class="btn float-right"
							   onclick="cleanFunction()"
							   value="CLEAN FILTERS" />
						<input type="submit"
							   value="SEARCH" 
							   id="SubmitFilter"
							   class="btn btn-primary float-right"/>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

CurrencyConverter/Views/Exchange/_StaticticCharts.cshtml
<hr />
<h1 class="text-center">Statistic</h1>
<div class="container">
	<div class="row">
		<div class="col-md-6">			
			<canvas id="chart_1" width="400" height="250"></canvas>
		</div>
		<div class="col-md-6">	
			<canvas id="chart_2" width="400" height="250"></canvas>
		</div>
	</div>	
</div>